"""LaunchAgent + Hermes skill installer, runnable from the UI (no terminal steps).

Everything is derived at runtime: the plugin directory from ``__file__``, the interpreter and import
path from the process that performs the install (the Hermes dashboard backend, the only Python known
to have fastapi/pydantic). Subprocess calls go through ``_run`` (the test seam).
"""

from __future__ import annotations

import os
import plistlib
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from . import db, errors

LABEL = "it.fl1.hermes-whatsapp-chat.channel"
SKILL_NAME = "whatsapp-chat"
SKILL_TOKEN = "{{WA_CLI}}"
_MINIMAL_PATH = "/usr/bin:/bin:/usr/sbin:/sbin"
_EXTRA_NODE_DIRS = ("/opt/homebrew/bin", "/usr/local/bin")


# --- Paths -----------------------------------------------------------------------


def plugin_dir() -> Path:
    """The installed plugin root: wa_core -> dashboard -> plugin."""
    return Path(__file__).resolve().parents[2]


def hermes_home() -> Path:
    return Path(os.environ.get("HERMES_HOME") or Path.home() / ".hermes")


def plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def skill_path() -> Path:
    return hermes_home() / "skills" / SKILL_NAME / "SKILL.md"


def launcher_paths() -> dict[str, Path]:
    bin_dir = db.data_dir() / "bin"
    return {"python": bin_dir / "hwc-python", "wa": bin_dir / "wa"}


def find_node() -> str | None:
    """Node binary: ``WA_NODE`` if usable, else PATH plus the usual install locations (a LaunchAgent/GUI
    process has a minimal PATH, so common dirs are searched explicitly)."""
    configured = os.environ.get("WA_NODE")
    if configured:
        found = shutil.which(configured)
        if found:
            return found
    dirs = [
        os.environ.get("PATH", ""),
        str(Path.home() / ".local" / "bin"),
        str(hermes_home() / "node" / "bin"),
        str(Path.home() / ".hermes" / "node" / "bin"),
        *_EXTRA_NODE_DIRS,
    ]
    return shutil.which("node", path=os.pathsep.join(d for d in dirs if d))


# --- Subprocess seam ------------------------------------------------------------------


def _run(argv: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True, timeout=30, check=False)


def _launchctl(argv: list[str]) -> subprocess.CompletedProcess | None:
    """Run launchctl; None when it cannot run at all (not macOS, timeout)."""
    try:
        return _run(["launchctl", *argv])
    except (OSError, subprocess.SubprocessError):
        return None


# --- Launchers -----------------------------------------------------------------------


def _write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)


def write_launchers(now: int | None = None) -> dict[str, str]:
    """Write ``<data>/bin/hwc-python`` (this process' interpreter + import path) and ``<data>/bin/wa``."""
    paths = launcher_paths()
    seen: set[str] = set()
    entries: list[str] = []
    for entry in sys.path:
        if entry and entry not in seen and os.path.isdir(entry):
            seen.add(entry)
            entries.append(entry)
    python_sh = (
        "#!/bin/sh\n"
        "# Generated by hermes-whatsapp-chat: Hermes' Python with the import path of the plugin backend.\n"
        f"export PYTHONPATH={shlex.quote(os.pathsep.join(entries))}\n"
        f"export HERMES_HOME={shlex.quote(str(hermes_home()))}\n"
        f"exec {shlex.quote(sys.executable)} \"$@\"\n"
    )
    wa_script = plugin_dir() / "scripts" / "wa.py"
    wa_sh = (
        "#!/bin/sh\n"
        "# Generated by hermes-whatsapp-chat: the WhatsApp chat CLI.\n"
        f"exec {shlex.quote(str(paths['python']))} {shlex.quote(str(wa_script))} \"$@\"\n"
    )
    _write_executable(paths["python"], python_sh)
    _write_executable(paths["wa"], wa_sh)
    return {"python": str(paths["python"]), "wa": str(paths["wa"])}


def wa_command() -> str:
    """Shell-ready absolute path of the ``wa`` launcher; launchers are written lazily when missing."""
    wa = launcher_paths()["wa"]
    if not wa.is_file():
        try:
            write_launchers()
        except OSError:
            pass
    return shlex.quote(str(wa))


# --- LaunchAgent -------------------------------------------------------------------


def service_installed() -> bool:
    return plist_path().is_file()


def install_service(*, now: int) -> dict[str, Any]:
    node = find_node()
    if not node:
        raise errors.Unavailable("Node.js not found: install Node 20+ (or set WA_NODE), then install the service again")
    launchers = write_launchers(now)
    plugin = plugin_dir()
    logs = db.data_dir() / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    env = {
        "WA_NODE": node,
        "HERMES_HOME": str(hermes_home()),
        "PATH": f"{Path(node).parent}:{_MINIMAL_PATH}",
    }
    if os.environ.get("WA_ARCHIVE_DB"):
        env["WA_ARCHIVE_DB"] = os.environ["WA_ARCHIVE_DB"]
    plist = {
        "Label": LABEL,
        "ProgramArguments": [launchers["python"], str(plugin / "sidecar" / "wa_channel.py"), "run"],
        "EnvironmentVariables": env,
        "WorkingDirectory": str(plugin),
        "RunAtLoad": True,
        "KeepAlive": True,
        "ThrottleInterval": 10,
        "StandardOutPath": str(logs / "channel.log"),
        "StandardErrorPath": str(logs / "channel.log"),
    }
    target = plist_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(plistlib.dumps(plist))
    domain = f"gui/{os.getuid()}"
    _launchctl(["bootout", f"{domain}/{LABEL}"])  # not loaded yet is fine
    result = _launchctl(["bootstrap", domain, str(target)])
    if result is None:
        raise errors.Unavailable("launchctl is not available: the background service needs macOS")
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip() or f"exit code {result.returncode}"
        raise errors.Unavailable(f"launchctl bootstrap failed: {detail}")
    return {"plist": str(target), "label": LABEL, "node": node, **launchers}


def uninstall_service() -> dict[str, Any]:
    _launchctl(["bootout", f"gui/{os.getuid()}/{LABEL}"])  # failure just means it was not loaded
    target = plist_path()
    existed = target.exists()
    target.unlink(missing_ok=True)
    return {"plist": str(target), "removed": existed}


# --- Hermes skill ------------------------------------------------------------------


def skill_installed() -> bool:
    return skill_path().is_file()


def install_skill(*, now: int) -> dict[str, str]:
    template = plugin_dir() / "skill" / SKILL_NAME / "SKILL.md"
    try:
        text = template.read_text(encoding="utf-8")
    except OSError as exc:
        raise errors.Unavailable(f"skill template missing: {template} ({exc})")
    write_launchers(now)
    target = skill_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text.replace(SKILL_TOKEN, wa_command()), encoding="utf-8")
    return {"path": str(target)}


def uninstall_skill() -> dict[str, bool]:
    target = skill_path()
    target.unlink(missing_ok=True)
    try:
        target.parent.rmdir()  # only if we left it empty
    except OSError:
        pass
    return {"ok": True}
