"""LaunchAgent + Hermes skill installer, runnable from the UI (no terminal steps).

Everything is derived at runtime: the plugin directory from ``__file__``, the interpreter and import
path from the process that performs the install (the Hermes dashboard backend, the only Python known
to have fastapi/pydantic). Subprocess calls go through ``_run`` (the test seam).
"""

from __future__ import annotations

import os
import plistlib
import shlex
import shutil
import sqlite3
import subprocess
import sys
from contextlib import closing
from pathlib import Path
from typing import Any

from . import db, errors

LABEL = "it.fl1.hermes-whatsapp-chat.channel"
SKILL_NAME = "whatsapp-chat"
SKILL_TOKEN = "{{WA_CLI}}"
_MINIMAL_PATH = "/usr/bin:/bin:/usr/sbin:/sbin"
_EXTRA_NODE_DIRS = ("/opt/homebrew/bin", "/usr/local/bin")

# Version of the HTTP route surface. Hermes mounts plugin routes only at server startup, so after a plugin
# update the UI can talk to the old backend still in memory: the UI compares this with its required
# version. BUMP IT ON ANY ROUTE CHANGE (new/removed/changed route or response shape the UI relies on).
API_VERSION = 3
# The service heartbeat is written every second; older than this means the service is not alive.
SERVICE_STALE_SECONDS = 15


# --- Paths -----------------------------------------------------------------------


def plugin_dir() -> Path:
    """The installed plugin root: wa_core -> dashboard -> plugin."""
    return Path(__file__).resolve().parents[2]


def hermes_home() -> Path:
    return Path(os.environ.get("HERMES_HOME") or Path.home() / ".hermes")


def plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def skill_path() -> Path:
    return hermes_home() / "skills" / SKILL_NAME / "SKILL.md"


def launcher_paths() -> dict[str, Path]:
    bin_dir = db.data_dir() / "bin"
    return {"python": bin_dir / "hwc-python", "wa": bin_dir / "wa"}


def find_node() -> str | None:
    """Node binary: ``WA_NODE`` if usable, else PATH plus the usual install locations (a LaunchAgent/GUI
    process has a minimal PATH, so common dirs are searched explicitly)."""
    configured = os.environ.get("WA_NODE")
    if configured:
        found = shutil.which(configured)
        if found:
            return found
    dirs = [
        os.environ.get("PATH", ""),
        str(Path.home() / ".local" / "bin"),
        str(hermes_home() / "node" / "bin"),
        str(Path.home() / ".hermes" / "node" / "bin"),
        *_EXTRA_NODE_DIRS,
    ]
    return shutil.which("node", path=os.pathsep.join(d for d in dirs if d))


# --- Subprocess seam ------------------------------------------------------------------


def _run(argv: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True, timeout=30, check=False)


def _launchctl(argv: list[str]) -> subprocess.CompletedProcess | None:
    """Run launchctl; None when it cannot run at all (not macOS, timeout)."""
    try:
        return _run(["launchctl", *argv])
    except (OSError, subprocess.SubprocessError):
        return None


# --- Launchers -----------------------------------------------------------------------


def _write_if_changed(path: Path, content: str | bytes, mode: int | None = None) -> bool:
    """Write ``content`` unless the file already has exactly it; True when it was (re)written."""
    data = content.encode("utf-8") if isinstance(content, str) else content
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        unchanged = path.read_bytes() == data
    except OSError:
        unchanged = False
    if not unchanged:
        path.write_bytes(data)
    if mode is not None and (not path.is_file() or path.stat().st_mode & 0o777 != mode):
        path.chmod(mode)
        return True
    return not unchanged


def _sync_launchers() -> tuple[dict[str, str], bool]:
    """Write ``<data>/bin/hwc-python`` (this process' interpreter + import path) and ``<data>/bin/wa``;
    also reports whether either file changed."""
    paths = launcher_paths()
    seen: set[str] = set()
    entries: list[str] = []
    for entry in sys.path:
        if entry and entry not in seen and os.path.isdir(entry):
            seen.add(entry)
            entries.append(entry)
    python_sh = (
        "#!/bin/sh\n"
        "# Generated by hermes-whatsapp-chat: Hermes' Python with the import path of the plugin backend.\n"
        f"export PYTHONPATH={shlex.quote(os.pathsep.join(entries))}\n"
        f"export HERMES_HOME={shlex.quote(str(hermes_home()))}\n"
        f"exec {shlex.quote(sys.executable)} \"$@\"\n"
    )
    wa_script = plugin_dir() / "scripts" / "wa.py"
    wa_sh = (
        "#!/bin/sh\n"
        "# Generated by hermes-whatsapp-chat: the WhatsApp chat CLI.\n"
        f"exec {shlex.quote(str(paths['python']))} {shlex.quote(str(wa_script))} \"$@\"\n"
    )
    changed_python = _write_if_changed(paths["python"], python_sh, 0o755)
    changed_wa = _write_if_changed(paths["wa"], wa_sh, 0o755)
    return {"python": str(paths["python"]), "wa": str(paths["wa"])}, changed_python or changed_wa


def write_launchers(now: int | None = None) -> dict[str, str]:
    """Write the launchers (see ``_sync_launchers``)."""
    return _sync_launchers()[0]


def wa_command() -> str:
    """Shell-ready absolute path of the ``wa`` launcher; launchers are written lazily when missing."""
    wa = launcher_paths()["wa"]
    if not wa.is_file():
        try:
            write_launchers()
        except OSError:
            pass
    return shlex.quote(str(wa))


# --- LaunchAgent -------------------------------------------------------------------


def service_installed() -> bool:
    return plist_path().is_file()


def _sync_service_files(node: str) -> tuple[dict[str, str], Path, bool]:
    """Write launchers + plist; returns (launcher paths, plist path, whether any of the three changed)."""
    launchers, launchers_changed = _sync_launchers()
    plugin = plugin_dir()
    logs = db.data_dir() / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    env = {
        "WA_NODE": node,
        "HERMES_HOME": str(hermes_home()),
        "PATH": f"{Path(node).parent}:{_MINIMAL_PATH}",
    }
    if os.environ.get("WA_ARCHIVE_DB"):
        env["WA_ARCHIVE_DB"] = os.environ["WA_ARCHIVE_DB"]
    plist = {
        "Label": LABEL,
        "ProgramArguments": [launchers["python"], str(plugin / "sidecar" / "wa_channel.py"), "run"],
        "EnvironmentVariables": env,
        "WorkingDirectory": str(plugin),
        "RunAtLoad": True,
        "KeepAlive": True,
        "ThrottleInterval": 10,
        "StandardOutPath": str(logs / "channel.log"),
        "StandardErrorPath": str(logs / "channel.log"),
    }
    target = plist_path()
    plist_changed = _write_if_changed(target, plistlib.dumps(plist))
    return launchers, target, launchers_changed or plist_changed


def _reload_service(target: Path) -> None:
    """Always (re)start the service: bootout + bootstrap, or ``kickstart -k`` when bootstrap says it is
    still loaded. Raises ``Unavailable`` when launchctl cannot run or both attempts fail."""
    domain = f"gui/{os.getuid()}"
    _launchctl(["bootout", f"{domain}/{LABEL}"])  # not loaded yet is fine
    result = _launchctl(["bootstrap", domain, str(target)])
    if result is None:
        raise errors.Unavailable("launchctl is not available: the background service needs macOS")
    if result.returncode == 0:
        return
    kick = _launchctl(["kickstart", "-k", f"{domain}/{LABEL}"])
    if kick is not None and kick.returncode == 0:
        return
    detail = (result.stderr or result.stdout or "").strip() or f"exit code {result.returncode}"
    raise errors.Unavailable(f"launchctl bootstrap failed: {detail}")


def install_service(*, now: int) -> dict[str, Any]:
    node = find_node()
    if not node:
        raise errors.Unavailable("Node.js not found: install Node 20+ (or set WA_NODE), then install the service again")
    launchers, target, _ = _sync_service_files(node)
    _reload_service(target)  # always restarts, even when nothing changed
    return {"plist": str(target), "label": LABEL, "node": node, **launchers}


def _heartbeat_at() -> int | None:
    with closing(db.connect()) as conn:
        row = conn.execute("SELECT heartbeat_at FROM service_status WHERE id = 1").fetchone()
    return row["heartbeat_at"] if row else None


def ensure_service(*, now: int) -> str:
    """Refresh an installed service after the plugin, Hermes or its interpreter changed.

    Called at every backend start: rewrites the launchers + plist from the running code and restarts the
    service when any file changed or its heartbeat is stale. Returns ``absent`` (no plist: never
    installed, nothing to do), ``ok``, ``restarted`` or ``error``."""
    if not service_installed():
        return "absent"
    try:
        node = find_node()
        if not node:
            return "error"
        _, target, changed = _sync_service_files(node)
        heartbeat = _heartbeat_at()
        stale = heartbeat is None or now - heartbeat > SERVICE_STALE_SECONDS
        if not (changed or stale):
            return "ok"
        _reload_service(target)
        return "restarted"
    except (errors.WaError, OSError, sqlite3.Error):
        return "error"


def uninstall_service() -> dict[str, Any]:
    _launchctl(["bootout", f"gui/{os.getuid()}/{LABEL}"])  # failure just means it was not loaded
    target = plist_path()
    existed = target.exists()
    target.unlink(missing_ok=True)
    return {"plist": str(target), "removed": existed}


# --- Hermes skill ------------------------------------------------------------------


def skill_installed() -> bool:
    return skill_path().is_file()


def install_skill(*, now: int) -> dict[str, str]:
    template = plugin_dir() / "skill" / SKILL_NAME / "SKILL.md"
    try:
        text = template.read_text(encoding="utf-8")
    except OSError as exc:
        raise errors.Unavailable(f"skill template missing: {template} ({exc})")
    write_launchers(now)
    target = skill_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text.replace(SKILL_TOKEN, wa_command()), encoding="utf-8")
    return {"path": str(target)}


def uninstall_skill() -> dict[str, bool]:
    target = skill_path()
    target.unlink(missing_ok=True)
    try:
        target.parent.rmdir()  # only if we left it empty
    except OSError:
        pass
    return {"ok": True}
